default:
  image: node:latest

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  paths:
    - node_modules/
    - .prisma/

build:
  stage: build
  script:
    - npx prisma generate
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .next/
      - .prisma/

deploy_preview:
  stage: deploy
  only:
    - develop
  script:
    - npm update
    - npm install -g vercel
    - $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Machine) + ";" + [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Process)
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel deploy --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm update
    - npm install -g vercel
    - $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Machine) + ";" + [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Process)
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel deploy --prod --token=$VERCEL_TOKEN